name: CMake on Linux (x86_64)

on:
  #push:
 #  branches: [ $default-branch ]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on:   [self-hosted, linux, x64, cuda]

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. 
      #Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:         #host,cuda,cuda_version           
         include:
          - host_compiler: "g++-13"
            cuda_version: "13.4"         
            opencv_version: "opencv-4.14.0-cuda134"             
          
    steps:    
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      run: |      
          echo "build-output-dir=${{github.workspace}}/build" >> "$GITHUB_OUTPUT"        
          echo "PATH=$HOME/cmake-4.4.0-linux-x86_64/bin/:$PATH" >> "$GITHUB_ENV"
          echo CUDACXX="/usr/local/cuda-${{matrix.cuda_version}}/bin/nvcc"  >> "$GITHUB_ENV"
          echo CC="${{matrix.host_compiler}}" >> "$GITHUB_ENV"
          echo CXX="${{matrix.host_compiler}}">> "$GITHUB_ENV"

    - name: Configure CMake      
      run: |                      
        cmake -G "Ninja" -B ${{steps.strings.outputs.build-output-dir}}  -DOPENCV_DIR="/usr/local/${{matrix.opencv_version}}" -DCMAKE_BUILD_TYPE="Release" -S ${{github.workspace}}       
 
    - name: Build     
      run: >                   
        cmake --build ${{ steps.strings.outputs.build-output-dir }} 
        --config Release
                     
    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config Release} --output-junit test_results.xml